timeout: 0

/spore
    protocol: limine
    path: boot():/boot/kernel.elf
    module_path: boot():/boot/init
    module_string: /init
    module_path: boot():/boot/bin/spore_demo
    module_string: /bin/spore_demo
    module_path: boot():/boot/exec_child
    module_string: /bin/exec_child
    module_path: boot():/boot/bin/ls
    module_string: /bin/ls
    module_path: boot():/boot/bin/cat
    module_string: /bin/cat
    module_path: boot():/boot/bin/echo
    module_string: /bin/echo
    module_path: boot():/boot/bin/mkdir
    module_string: /bin/mkdir
    module_path: boot():/boot/bin/rm
    module_string: /bin/rm
    module_path: boot():/boot/bin/touch
    module_string: /bin/touch
    module_path: boot():/boot/bin/pwd
    module_string: /bin/pwd
    module_path: boot():/boot/bin/hello
    module_string: /bin/hello
    module_path: boot():/boot/hello
    module_string: /hello
    module_path: boot():/boot/bin/true
    module_string: /bin/true
    module_path: boot():/boot/bin/false
    module_string: /bin/false
    module_path: boot():/boot/bin/spinner
    module_string: /bin/spinner
    module_path: boot():/boot/bin/peeker
    module_string: /bin/peeker
    module_path: boot():/boot/bin/writer
    module_string: /bin/writer
    module_path: boot():/boot/bin/memhog
    module_string: /bin/memhog
    module_path: boot():/boot/bin/escalate
    module_string: /bin/escalate
    cmdline: log=debug
    randomise_hhdm_base: no
    kaslr: no
    paging_mode: 4level
